version: "3"

tasks:

  hm-switch:
    cmds:
      - home-manager switch --flake .#jonas-desktop

  flake-update:
    cmds:
      - nix flake update

  flake-update-branch:
    cmds:
      - git checkout -b feature/update-flakes-$(date +"%d%m%y")

  flake-update-push:
    cmds:
      - gh pr create --title "Flake lock file updates" --body "Regular maintenence updates in order to keep packages up to date." --label "flake-update"

  get-vscode-extension-updates:
    cmds:
      - ./vscode_updater.py

  format:
    cmds:
      - nix fmt
